/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SinaisRouteImport } from './routes/sinais'
import { Route as RiscosOnlineRouteImport } from './routes/riscos-online'
import { Route as RelatorioSeoRouteImport } from './routes/relatorio-seo'
import { Route as PaisRouteImport } from './routes/pais'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MaioLaranjaRouteImport } from './routes/maio-laranja'
import { Route as LegislacaoRouteImport } from './routes/legislacao'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as DenunciaRouteImport } from './routes/denuncia'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as CasosSlugRouteImport } from './routes/casos.$slug'
import { Route as BibliotecaSlugRouteImport } from './routes/biblioteca.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin/usuarios/index'
import { Route as AuthenticatedAdminMapaIndexRouteImport } from './routes/_authenticated/admin/mapa/index'
import { Route as AuthenticatedAdminBibliotecaIndexRouteImport } from './routes/_authenticated/admin/biblioteca/index'
import { Route as AuthenticatedAdminMapaIdRouteImport } from './routes/_authenticated/admin/mapa/$id'
import { Route as AuthenticatedAdminBibliotecaIdRouteImport } from './routes/_authenticated/admin/biblioteca/$id'
import { Route as AuthenticatedAdminArticleIdRouteImport } from './routes/_authenticated/admin/article.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SinaisRoute = SinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscosOnlineRoute = RiscosOnlineRouteImport.update({
  id: '/riscos-online',
  path: '/riscos-online',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioSeoRoute = RelatorioSeoRouteImport.update({
  id: '/relatorio-seo',
  path: '/relatorio-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisRoute = PaisRouteImport.update({
  id: '/pais',
  path: '/pais',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MaioLaranjaRoute = MaioLaranjaRouteImport.update({
  id: '/maio-laranja',
  path: '/maio-laranja',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislacaoRoute = LegislacaoRouteImport.update({
  id: '/legislacao',
  path: '/legislacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciaRoute = DenunciaRouteImport.update({
  id: '/denuncia',
  path: '/denuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const CasosSlugRoute = CasosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasosRoute,
} as any)
const BibliotecaSlugRoute = BibliotecaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibliotecaRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMapaIndexRoute =
  AuthenticatedAdminMapaIndexRouteImport.update({
    id: '/mapa/',
    path: '/mapa/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBibliotecaIndexRoute =
  AuthenticatedAdminBibliotecaIndexRouteImport.update({
    id: '/biblioteca/',
    path: '/biblioteca/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMapaIdRoute =
  AuthenticatedAdminMapaIdRouteImport.update({
    id: '/mapa/$id',
    path: '/mapa/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBibliotecaIdRoute =
  AuthenticatedAdminBibliotecaIdRouteImport.update({
    id: '/biblioteca/$id',
    path: '/biblioteca/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminArticleIdRoute =
  AuthenticatedAdminArticleIdRouteImport.update({
    id: '/article/$id',
    path: '/article/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/casos': typeof CasosRouteWithChildren
  '/como-ajudar': typeof ComoAjudarRoute
  '/denuncia': typeof DenunciaRoute
  '/escolas': typeof EscolasRoute
  '/faq': typeof FaqRoute
  '/fontes': typeof FontesRoute
  '/legislacao': typeof LegislacaoRoute
  '/maio-laranja': typeof MaioLaranjaRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/objetivos': typeof ObjetivosRoute
  '/pais': typeof PaisRoute
  '/relatorio-seo': typeof RelatorioSeoRoute
  '/riscos-online': typeof RiscosOnlineRoute
  '/sinais': typeof SinaisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/casos/$slug': typeof CasosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/article/$id': typeof AuthenticatedAdminArticleIdRoute
  '/admin/biblioteca/$id': typeof AuthenticatedAdminBibliotecaIdRoute
  '/admin/mapa/$id': typeof AuthenticatedAdminMapaIdRoute
  '/admin/biblioteca/': typeof AuthenticatedAdminBibliotecaIndexRoute
  '/admin/mapa/': typeof AuthenticatedAdminMapaIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/casos': typeof CasosRouteWithChildren
  '/como-ajudar': typeof ComoAjudarRoute
  '/denuncia': typeof DenunciaRoute
  '/escolas': typeof EscolasRoute
  '/faq': typeof FaqRoute
  '/fontes': typeof FontesRoute
  '/legislacao': typeof LegislacaoRoute
  '/maio-laranja': typeof MaioLaranjaRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/objetivos': typeof ObjetivosRoute
  '/pais': typeof PaisRoute
  '/relatorio-seo': typeof RelatorioSeoRoute
  '/riscos-online': typeof RiscosOnlineRoute
  '/sinais': typeof SinaisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/casos/$slug': typeof CasosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/article/$id': typeof AuthenticatedAdminArticleIdRoute
  '/admin/biblioteca/$id': typeof AuthenticatedAdminBibliotecaIdRoute
  '/admin/mapa/$id': typeof AuthenticatedAdminMapaIdRoute
  '/admin/biblioteca': typeof AuthenticatedAdminBibliotecaIndexRoute
  '/admin/mapa': typeof AuthenticatedAdminMapaIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/casos': typeof CasosRouteWithChildren
  '/como-ajudar': typeof ComoAjudarRoute
  '/denuncia': typeof DenunciaRoute
  '/escolas': typeof EscolasRoute
  '/faq': typeof FaqRoute
  '/fontes': typeof FontesRoute
  '/legislacao': typeof LegislacaoRoute
  '/maio-laranja': typeof MaioLaranjaRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/objetivos': typeof ObjetivosRoute
  '/pais': typeof PaisRoute
  '/relatorio-seo': typeof RelatorioSeoRoute
  '/riscos-online': typeof RiscosOnlineRoute
  '/sinais': typeof SinaisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/casos/$slug': typeof CasosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/article/$id': typeof AuthenticatedAdminArticleIdRoute
  '/_authenticated/admin/biblioteca/$id': typeof AuthenticatedAdminBibliotecaIdRoute
  '/_authenticated/admin/mapa/$id': typeof AuthenticatedAdminMapaIdRoute
  '/_authenticated/admin/biblioteca/': typeof AuthenticatedAdminBibliotecaIndexRoute
  '/_authenticated/admin/mapa/': typeof AuthenticatedAdminMapaIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/casos'
    | '/como-ajudar'
    | '/denuncia'
    | '/escolas'
    | '/faq'
    | '/fontes'
    | '/legislacao'
    | '/maio-laranja'
    | '/mapa'
    | '/metodologia'
    | '/noticias'
    | '/objetivos'
    | '/pais'
    | '/relatorio-seo'
    | '/riscos-online'
    | '/sinais'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/biblioteca/$slug'
    | '/casos/$slug'
    | '/noticias/$slug'
    | '/admin/'
    | '/admin/article/$id'
    | '/admin/biblioteca/$id'
    | '/admin/mapa/$id'
    | '/admin/biblioteca/'
    | '/admin/mapa/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/casos'
    | '/como-ajudar'
    | '/denuncia'
    | '/escolas'
    | '/faq'
    | '/fontes'
    | '/legislacao'
    | '/maio-laranja'
    | '/mapa'
    | '/metodologia'
    | '/noticias'
    | '/objetivos'
    | '/pais'
    | '/relatorio-seo'
    | '/riscos-online'
    | '/sinais'
    | '/sitemap.xml'
    | '/sobre'
    | '/biblioteca/$slug'
    | '/casos/$slug'
    | '/noticias/$slug'
    | '/admin'
    | '/admin/article/$id'
    | '/admin/biblioteca/$id'
    | '/admin/mapa/$id'
    | '/admin/biblioteca'
    | '/admin/mapa'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/biblioteca'
    | '/casos'
    | '/como-ajudar'
    | '/denuncia'
    | '/escolas'
    | '/faq'
    | '/fontes'
    | '/legislacao'
    | '/maio-laranja'
    | '/mapa'
    | '/metodologia'
    | '/noticias'
    | '/objetivos'
    | '/pais'
    | '/relatorio-seo'
    | '/riscos-online'
    | '/sinais'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/biblioteca/$slug'
    | '/casos/$slug'
    | '/noticias/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/article/$id'
    | '/_authenticated/admin/biblioteca/$id'
    | '/_authenticated/admin/mapa/$id'
    | '/_authenticated/admin/biblioteca/'
    | '/_authenticated/admin/mapa/'
    | '/_authenticated/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  CasosRoute: typeof CasosRouteWithChildren
  ComoAjudarRoute: typeof ComoAjudarRoute
  DenunciaRoute: typeof DenunciaRoute
  EscolasRoute: typeof EscolasRoute
  FaqRoute: typeof FaqRoute
  FontesRoute: typeof FontesRoute
  LegislacaoRoute: typeof LegislacaoRoute
  MaioLaranjaRoute: typeof MaioLaranjaRoute
  MapaRoute: typeof MapaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ObjetivosRoute: typeof ObjetivosRoute
  PaisRoute: typeof PaisRoute
  RelatorioSeoRoute: typeof RelatorioSeoRoute
  RiscosOnlineRoute: typeof RiscosOnlineRoute
  SinaisRoute: typeof SinaisRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinais': {
      id: '/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof SinaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riscos-online': {
      id: '/riscos-online'
      path: '/riscos-online'
      fullPath: '/riscos-online'
      preLoaderRoute: typeof RiscosOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-seo': {
      id: '/relatorio-seo'
      path: '/relatorio-seo'
      fullPath: '/relatorio-seo'
      preLoaderRoute: typeof RelatorioSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pais': {
      id: '/pais'
      path: '/pais'
      fullPath: '/pais'
      preLoaderRoute: typeof PaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maio-laranja': {
      id: '/maio-laranja'
      path: '/maio-laranja'
      fullPath: '/maio-laranja'
      preLoaderRoute: typeof MaioLaranjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislacao': {
      id: '/legislacao'
      path: '/legislacao'
      fullPath: '/legislacao'
      preLoaderRoute: typeof LegislacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncia': {
      id: '/denuncia'
      path: '/denuncia'
      fullPath: '/denuncia'
      preLoaderRoute: typeof DenunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/casos/$slug': {
      id: '/casos/$slug'
      path: '/$slug'
      fullPath: '/casos/$slug'
      preLoaderRoute: typeof CasosSlugRouteImport
      parentRoute: typeof CasosRoute
    }
    '/biblioteca/$slug': {
      id: '/biblioteca/$slug'
      path: '/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof BibliotecaSlugRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mapa/': {
      id: '/_authenticated/admin/mapa/'
      path: '/mapa'
      fullPath: '/admin/mapa/'
      preLoaderRoute: typeof AuthenticatedAdminMapaIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/biblioteca/': {
      id: '/_authenticated/admin/biblioteca/'
      path: '/biblioteca'
      fullPath: '/admin/biblioteca/'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mapa/$id': {
      id: '/_authenticated/admin/mapa/$id'
      path: '/mapa/$id'
      fullPath: '/admin/mapa/$id'
      preLoaderRoute: typeof AuthenticatedAdminMapaIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/biblioteca/$id': {
      id: '/_authenticated/admin/biblioteca/$id'
      path: '/biblioteca/$id'
      fullPath: '/admin/biblioteca/$id'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/article/$id': {
      id: '/_authenticated/admin/article/$id'
      path: '/article/$id'
      fullPath: '/admin/article/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticleIdRoute: typeof AuthenticatedAdminArticleIdRoute
  AuthenticatedAdminBibliotecaIdRoute: typeof AuthenticatedAdminBibliotecaIdRoute
  AuthenticatedAdminMapaIdRoute: typeof AuthenticatedAdminMapaIdRoute
  AuthenticatedAdminBibliotecaIndexRoute: typeof AuthenticatedAdminBibliotecaIndexRoute
  AuthenticatedAdminMapaIndexRoute: typeof AuthenticatedAdminMapaIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminArticleIdRoute: AuthenticatedAdminArticleIdRoute,
    AuthenticatedAdminBibliotecaIdRoute: AuthenticatedAdminBibliotecaIdRoute,
    AuthenticatedAdminMapaIdRoute: AuthenticatedAdminMapaIdRoute,
    AuthenticatedAdminBibliotecaIndexRoute:
      AuthenticatedAdminBibliotecaIndexRoute,
    AuthenticatedAdminMapaIndexRoute: AuthenticatedAdminMapaIndexRoute,
    AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BibliotecaRouteChildren {
  BibliotecaSlugRoute: typeof BibliotecaSlugRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaSlugRoute: BibliotecaSlugRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface CasosRouteChildren {
  CasosSlugRoute: typeof CasosSlugRoute
}

const CasosRouteChildren: CasosRouteChildren = {
  CasosSlugRoute: CasosSlugRoute,
}

const CasosRouteWithChildren = CasosRoute._addFileChildren(CasosRouteChildren)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  CasosRoute: CasosRouteWithChildren,
  ComoAjudarRoute: ComoAjudarRoute,
  DenunciaRoute: DenunciaRoute,
  EscolasRoute: EscolasRoute,
  FaqRoute: FaqRoute,
  FontesRoute: FontesRoute,
  LegislacaoRoute: LegislacaoRoute,
  MaioLaranjaRoute: MaioLaranjaRoute,
  MapaRoute: MapaRoute,
  MetodologiaRoute: MetodologiaRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  ObjetivosRoute: ObjetivosRoute,
  PaisRoute: PaisRoute,
  RelatorioSeoRoute: RelatorioSeoRoute,
  RiscosOnlineRoute: RiscosOnlineRoute,
  SinaisRoute: SinaisRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
